### PR TITLE
Port neurodesign to Python 3

### PR DESCRIPTION
**Pull request by lukassnoek**
Hi!

Thanks for developing this great package! I would like to use this package in our computer labs of our course "Neuroimaging: BOLD" at the University of Amsterdam, but we're using Python 3.6. As such, I created a version of `neurodesign` that both works with Python2 and Python3. With "works with Py2/3", I mean that all examples in the `examples/` folder seem to run.

Apart from some syntax/functionality changes (e.g., using `range` instead of `xrange`), I've slightly restructured the package (e.g., rename the `src` directory and move it to the root of the package).

Let me know if you'd be willing to merge this into the original repo. If not, no worries, I'll just use my fork for the course we're teaching.

Cheers,
Lukas

### CODE REVIEW

**Comment by jokedurnez** [comment]
This is so cool ! I'll test it later this week !

**Comment by PeerHerholz** [comment]
Hi @lukassnoek and @jokedurnez,

in response to #3 I did some small changes, but didn't check with @lukassnoek's PR before I submitted [mine](https://github.com/neuropower/neurodesign/pull/9). Seems like he already did everything (and way more), hence: should I delete mine? Sorry for the inconvenience.

**Comment by lukassnoek** [comment]
Haven't heard back from @jokedurnez . Haven't tested whether my implementation still works though.

**Comment by jokedurnez** [comment]
I'm so sorry, I'm swamped with work lately.  Gonna prioritize this for the end of the summer.

**Comment by Remi-Gau** [comment]
all examples still run

**Review by Remi-Gau — APPROVED** [review]

**Pull request merged**
